# Ubuntu apt 更新镜像地址
# UBUNTU_MIRROR="mirrors.ustc.edu.cn"
UBUNTU_MIRROR="mirrors.aliyun.com"

# GitHub 代码镜像地址，按顺序尝试，全部失败后回退原始地址
GITHUB_GIT_MIRRORS=(
    "https://gitclone.com/github.com/"
    "https://kkgithub.com/"
    "https://gh.llkk.cc/https://github.com/"
    "https://gh-proxy.com/https://github.com/"
    "https://ghproxy.net/https://github.com/"
)

# GitHub 制品镜像地址，按顺序尝试，全部失败后回退原始地址
GITHUB_RELEASES_MIRRORS=(
    "https://mirrors.tuna.tsinghua.edu.cn/github-release/"
    "https://mirror.ghproxy.com/"
    "https://gh.llkk.cc/"
    "https://gh-proxy.com/"
    "https://ghproxy.net/"
)

# Docker 镜像拉取加速地址，预拉成功后会标记为标准镜像名，并删除加速镜像标签
DOCKER_IMAGE_PULL_MIRRORS=(
    "docker.m.daocloud.io"
    "docker.1ms.run"
    "docker.xuanyuan.me"
    "dockerproxy.net"
    "docker.chenby.cn"
)
